# Generated by Django 5.1.3 on 2024-11-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Text',
            new_name='text',
        ),
    ]
