# Generated by Django 5.1.3 on 2024-11-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_text_choice_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('url_background', models.CharField(default='', max_length=255)),
                ('url_text_box', models.CharField(default='', max_length=255)),
                ('url_character_left', models.CharField(default='', max_length=255)),
                ('url_character_middle', models.CharField(default='', max_length=255)),
                ('url_character_right', models.CharField(default='', max_length=255)),
                ('text', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
