# Generated by Django 5.1.3 on 2024-12-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_scene_url_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='url_background',
            field=models.CharField(default='', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='url_character_left',
            field=models.CharField(default='', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='url_character_middle',
            field=models.CharField(default='', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='url_character_right',
            field=models.CharField(default='', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='url_text_box',
            field=models.CharField(default='', max_length=1023, null=True),
        ),
    ]
