# Generated by Django 5.1.5 on 2025-02-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_scene_url_background_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_value', models.DecimalField(decimal_places=2, help_text='Insira uma nota de 0 a 100', max_digits=5, verbose_name='Nota')),
                ('feedback', models.TextField(blank=True, help_text='Comentários sobre o desempenho do projeto', null=True, verbose_name='Feedback')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.project', verbose_name='Projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
