# Generated by Django 5.1.3 on 2024-11-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_scene'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
