# Generated by Django 5.1.3 on 2024-11-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='from_scene',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='from_scene', to='api.scene'),
        ),
        migrations.AddField(
            model_name='choice',
            name='to_scene',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_scene', to='api.scene'),
        ),
        migrations.AddField(
            model_name='project',
            name='first_scene',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.scene'),
        ),
    ]
