# Generated by Django 5.1.3 on 2024-12-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='private',
        ),
        migrations.AddField(
            model_name='project',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='text',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='url_background',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='url_character_left',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='url_character_middle',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='url_character_right',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='url_text_box',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
