# Generated by Django 5.1.3 on 2024-12-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('api', '0008_remove_project_private_project_privacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
