# Generated by Django 5.1.3 on 2024-12-10 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_genre_project_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='project',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='api.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='first_scene',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_scene_for_project', to='api.scene'),
        ),
    ]
