# Generated by Django 5.1.3 on 2024-12-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_genre_rename_private_project_privacy_scene_project_and_more'),
        ('api', '0011_scene_project_alter_project_first_scene'),
    ]

    operations = [
    ]
