-- MySQL Script generated by MySQL Workbench
-- seg 21 out 2024 21:03:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Scene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scene` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Background` VARCHAR(45) NULL,
  `Character_Left` VARCHAR(45) NULL,
  `Character_Middle` VARCHAR(45) NULL,
  `Character_Right` VARCHAR(45) NULL,
  `Text` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Date_of_Creation` DATE NOT NULL,
  PRIMARY KEY (`ID`, `Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `User_Name` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Avaiability` VARCHAR(45) NOT NULL,
  `Creation` DATE NOT NULL,
  `Update` DATE NULL,
  `First_Scene_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `User_ID`, `User_Name`),
  INDEX `fk_Project_Scene1_idx` (`First_Scene_ID` ASC) VISIBLE,
  INDEX `fk_Project_User1_idx` (`User_ID` ASC, `User_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Project_Scene1`
    FOREIGN KEY (`First_Scene_ID`)
    REFERENCES `mydb`.`Scene` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_User1`
    FOREIGN KEY (`User_ID` , `User_Name`)
    REFERENCES `mydb`.`User` (`ID` , `Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Choice` (
  `ID` INT NOT NULL,
  `Text` VARCHAR(45) NOT NULL,
  `Scene_ID` INT NOT NULL,
  `Next_Scene_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Next_Scene_ID`, `Scene_ID`),
  INDEX `fk_Choice_Scene1_idx` (`Scene_ID` ASC) VISIBLE,
  INDEX `fk_Choice_Scene2_idx` (`Next_Scene_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Choice_Scene1`
    FOREIGN KEY (`Scene_ID`)
    REFERENCES `mydb`.`Scene` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Choice_Scene2`
    FOREIGN KEY (`Next_Scene_ID`)
    REFERENCES `mydb`.`Scene` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
